GET http://localhost:8003/batch/hello
Accept: application/json

###
GET http://localhost:8000/batch/hello
Accept: application/json

###

POST http://localhost:8002/business/admin/train/query-all

###
GET http://localhost:8002/business/admin/train-station/query-list?pageNum=1&pageSize=2


###
GET http://localhost:8002/business/admin/train-carriage/query-list?pageNum=1&pageSize=2

###
GET http://localhost:8002/business/admin/train-seat/query-list?pageNum=1&pageSize=2