
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13399292922",
  "code": "8888"
}

> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.content.token));
    client.global.set("token", response.body.content.token);
%}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1936352722223763456,
  "memberId": 1931638920441892864,
  "name": "testxiaoming",
  "idCard": "1234",
  "type": "1"
}


###
GET http://localhost:8000/member/passenger/queryList?pageNum=1&pageSize=2
Accept: application/json
token: {{token}}



###
POST http://localhost:8000/member/passenger/delete/1936352722223763456
Accept: application/json
token: {{token}}